version: '3.8'
services:
  mysql:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=default_password
      - MYSQL_DATABASE=checkpoint
    volumes:
      - mysql:/var/lib/mysql
  minio:
    image: 'docker.io/bitnami/minio:2020-debian-10'
    ports:
      - '9000:9000'
    environment:
      - MINIO_API_CORS_ALLOW_ORIGIN=*
    volumes:
      - ./data:/data
volumes:
  mysql:
    driver: local
